# Lab 1  : 텐서플로 기본연산하기

## 텐서플로 설치 확인 (텐서플로의 Hello World!)

In [1]:
import tensorflow as tf

Hello Tensorflow!!라는 상수값을 hello상수변수에 저장한다

In [2]:
hello = tf.constant('Hello Tensorflow!!')     #대입연산

상수변수 hello를 print함수로 출력해본다

In [3]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [4]:
a = tf.constant(3)
b = tf.constant(5)
c = a + b
d = c * 3 + a

In [5]:
sess = tf.Session()

In [6]:
result = sess.run(c)

In [7]:
print(result)

8


"Hello Tensorflow!!"라는 문자열이 출력되지 않고, 대입연산의 출력결과인 텐서의 형태만 반환이 된다. 
이는 아직 hello상수에 값이 대입되지 않았기 때문이다. 즉, hello상수에 값을 대입하는 연산(operation)은 아직 
수행되지 않았고, 대입연산에 대한 정의만 graph에 추가된 것이다. (graph에 대한 설명은 밑에서).
"Const:0"에서 ":0"은 출력을 의미한다. 출력의 shape은 1차원이고, 자료형(dtype)은 string이다.

정의한 대입연산이 수행되려면 먼저 세션을 열어야 한다:

In [8]:
sess = tf.Session()

세션 sess을 이용하여 hello라는 값이 연산되도록 sess의 run함수를 실행하여 실행결과인 hello의 값을 result변수에
저장한다. 

In [9]:
result = sess.run(hello)

result변수를 출력하면 "Hello Tensorflow!!"라는 문자열이 출력되는 것을 볼 수 있다.

In [10]:
print(result)

b'Hello Tensorflow!!'


## 텐서플로의 자료형

### 자료형 관련 내용은 조대협님 블로그(http://bcho.tistory.com/1153) 에서 발췌하였습니다. 

### 상수형

간단한 수식에 대해서 다시 한번 확인. python의 수식의 결과는 다음과 같다.

In [11]:
x = 1
print(x)

1


In [12]:
y = x+9
print(y)

10


반면 tensorflow라이브러리를 이용한 연산결과는 다음과 같다. 마찬가지로 출력결과에 대한 형태만 출력된다.

In [13]:
x = tf.constant(1,name = 'x')
print(x)

Tensor("x:0", shape=(), dtype=int32)


다음과 같이 세션을 열어서 x값을 출력하도록 한다. 

In [14]:
sess = tf.Session()
result = sess.run(x)
print(result)

1


### 변수형

 이번에는 변수형인 y를 선언하고 x+9라는 값을 할당해보자.

In [15]:
x = tf.constant(1,name = 'x')
y = tf.Variable(x+9,name = 'y') #변수형은 Variable로 선언된다.

다음과 같이 y변수를 출력하면 형태만 출력이 된다.

In [16]:
print(y)

상수형때와 마찬가지로 세션을 열어서 출력을 시도해본다.

In [17]:
sess = tf.Session()
result = sess.run(y)
print(result)

FailedPreconditionError: Attempting to use uninitialized value y
	 [[Node: _send_y_0 = _Send[T=DT_INT32, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=-6536330151279835044, tensor_name="y:0", _device="/job:localhost/replica:0/task:0/cpu:0"](y)]]

그런데 위의 코드를 실행시켜보면 에러가 난다. 이는 변수의 경우 초기화하는 연산을 먼저 수행해야 하기 때문이다. 아래 코드는 변수의 초기화를 먼저 수행하여 에러가 나지 않음. 여기서 초기화되는 변수는 위에서 tf.Variable형인 y이다.

In [18]:
sess = tf.Session()
init = tf.initialize_all_variables()  #변수들을 초기화하는 연산을 정의함
sess.run(init)   # 변수의 초기화를 먼저 수행함. 
result = sess.run(y)
print(result)

10


### Placeholder(플레이스홀더)

플레이스 홀더란 (나중에 주로 훈련용으로 사용될) 입력데이타를 넣는 변수이다. 이때의 입력데이타는 세션을 run하는 시점에서 feeding(입력)된다.

In [19]:
import tensorflow as tf
input_data = [1,2,3,4,5]
input_data2 = [3,5,7,9,11]

x = tf.placeholder(dtype=tf.float32)
y = x * 2  #여기서 y는 Variables으로 선언되지 않았기 때문에 이후에 이를 먼저 초기화하지 않아도 에러가 안남

sess = tf.Session()

result = sess.run(y,feed_dict={x:input_data})
print (result)

# 입력데이타를 바꿔서 피딩한 후에 다시 run시키면 출력결과가 달라진다.
result = sess.run(y,feed_dict={x:input_data2})  
print (result)

[  2.   4.   6.   8.  10.]
[  6.  10.  14.  18.  22.]


이번에 다시 Variable을 사용하여 돌려보자. 밑의 코드에서 주의해야 할 점은 W에 2라는 값이 지정이 되려면 먼저 변수를 초기화시키는 명령문을 한번 돌려야 한다는 것이다.

In [20]:
import tensorflow as tf
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([2],dtype=tf.float32) #W에 2라는 값이 지정되려면 세션을 돌리기 전에 변수를 초기화해야 한다.
y = W*x

sess = tf.Session()

init = tf.initialize_all_variables() #변수를 초기화하는 과정
sess.run(init)

result = sess.run(y,feed_dict={x:input_data})

print(result)

[  2.   4.   6.   8.  10.]


## 연습 #1 : 원하는 연산을 정의하고 출력해보기 (10분)

In [3]:
## 연습 #1

## 행렬

다음 코드는 그림과 같은 1x3 상수벡터를 3x1상수벡터와 곱하는 예를 보이고 있다.

![title](img/Day1-1-2.png)

In [21]:
import tensorflow as tf
x = tf.constant([[1.0,2.0,3.0]] )        # 1x3 상수 벡터
print('x벡터의 형태:')
print(x.get_shape())

w = tf.constant([ [2.0],[2.0],[2.0] ])    # 3x1 상수 벡터
print('w벡터의 형태:')
print(w.get_shape())

y = tf.matmul(x,w)                        # x벡터와 w벡터의 곱(내적)    

sess = tf.Session()
init = tf.initialize_all_variables() #변수를 초기화하는 과정
sess.run(init)
result = sess.run(y)

print('x와 w벡터의 곱:')
print(result)

x벡터의 형태:
(1, 3)
w벡터의 형태:
(3, 1)
x와 w벡터의 곱:
[[ 12.]]


다음은 3x3행렬을 3x1행렬과 곱하는 예를 보이고 있다.

![title](img/Day1-1-3.png)

코드는 다음과 같다:

In [22]:
import tensorflow as tf
input_data = [ [1.,2.,3.],[1.,2.,3.],[2.,3.,4.] ] #3x3 matrix

x = tf.placeholder(dtype=tf.float32,shape=[None,3])
w = tf.Variable([ [2.],[2.],[2.] ], dtype = tf.float32) #3x1 matrix
y = tf.matmul(x,w)

sess = tf.Session()

init = tf.initialize_all_variables() #변수를 초기화하는 과정
sess.run(init)

result = sess.run(y,feed_dict={x:input_data})

print (result)

[[ 12.]
 [ 12.]
 [ 18.]]


위에서 x행렬의 크기가 Nonex3으로 정의되어 있는데, 여기서 Nonex3이란 세션을 run시킬 때 입력되는 행렬의 크기가 1x3, 2x3, 3x3,....100x3 등 None에 해당하는 열의 크기가 임의의 크기라도 다 될 수 있다는 뜻이다. 즉, 밑의 코드처럼 x의 입력으로 3x3행렬을 feed할 수도 있지만, 1x3행렬을 feed할 수도 있다:

In [23]:
import tensorflow as tf
input_data1 = [ [1.,2.,3.],[1.,2.,3.],[2.,3.,4.] ] #3x3 matrix
input_data2 = [[1.,2.,3.]] #1x3 matrix
x = tf.placeholder(dtype=tf.float32,shape=[None,3])
w = tf.Variable([ [2.],[2.],[2.] ], dtype = tf.float32) #3x1 matrix
y = tf.matmul(x,w)

sess = tf.Session()

init = tf.initialize_all_variables() #변수를 초기화하는 과정
sess.run(init)

result1 = sess.run(y,feed_dict={x:input_data1})
print (result1)

result2 = sess.run(y,feed_dict={x:input_data2})
print(result2)

[[ 12.]
 [ 12.]
 [ 18.]]
[[ 12.]]


이는 입력되는 데이타셋의 크기에 상관없이 코드가 돌아갈 수 있게 하기 위한 것이다.

## 브로드캐스팅 (Broadcasting)

In [24]:
import tensorflow as tf
input_data = [
     [1,1,1],[2,2,2]
    ]
x = tf.placeholder(dtype=tf.float32,shape=[2,3])  # 2x3행렬
w  =tf.Variable([[2],[2],[2]],dtype=tf.float32)  # 3x1행렬
b  =tf.Variable([4],dtype=tf.float32)            # 1x1행렬
y = tf.matmul(x,w)+b    # 2x3행렬 곱하기 3x1행렬 + 1x1행렬 : 브로드캐스팅에 의해 1x1행렬-> 2x1행렬로 늘어남.

print (x.get_shape())
sess = tf.Session()
init = tf.initialize_all_variables() #변수를 초기화하는 과정
sess.run(init)
result = sess.run(y,feed_dict={x:input_data})

print (result)

(2, 3)
[[ 10.]
 [ 16.]]


위의 코드에서 x는 2x3행렬이고, w는 3x1행렬이다. 이 둘을 곱하면 2x1 행렬이 된다. 그런데 여기에 b행렬을 더하게 되는데, b는 1x1크기이기 때문에 원래는 더해질 수 없다. 이때 b행렬의 크기를 늘리게 된다. 이를 broadcasting이라고 한다. 여기서 broad란 넓다는 뜻으로 행렬의 크기를 늘릴 수는 있지만 줄이지는 못한다. 텐서플로에서 Broadcasting의 원리는 numpy array의 broadcasting의 원리를 그대로 따른다(http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc). broadcasting이 되려면 연산을 주도하는 축이 일치하거나, 1이어야 한다.  

![title](img/broadcasting1.gif)

위 그림은 4x3행렬과 1x3행렬의 더하기 연산을 시도하고 있다. 이때 더하기 연산은 행렬의 열원소에 대해 이루어지는데, 그러므로 열이 연산의 주축이라고 할 수 있고, 위에서 열의 갯수는 3으로 동일하다. 그러므로 broadcasting이 일어날 수 있고, 행을 복사하여 늘리는 broadcasting이 일어나게 된다.

In [25]:
#import tensorflow as tf

a  =tf.Variable([[0,0,0],[10,10,10],[20,20,20],[30,30,30]],dtype=tf.float32)  # 4x3행렬
b  =tf.Variable([[0,1,2]],dtype=tf.float32) # 1x4행렬  
y  = a+b   # 4x3행렬 + 1x3행렬
                                      #브로드캐스팅에 의해 1x3행렬-> 4x3행렬로 늘어남.
sess = tf.Session()
init = tf.initialize_all_variables() #변수를 초기화하는 과정
sess.run(init)
result = sess.run(y)

print (result)

[[  0.   1.   2.]
 [ 10.  11.  12.]
 [ 20.  21.  22.]
 [ 30.  31.  32.]]


또는 행의 갯수가 맞춰져 있으면 자동으로 열의 갯수를 맞추는 broadcasting도 일어난다.

In [26]:
import tensorflow as tf

a  =tf.Variable([[0,0,0],[10,10,10],[20,20,20],[30,30,30]],dtype=tf.float32)  # 4x3행렬
b  =tf.Variable([[0],[0],[0],[0]],dtype=tf.float32) # 4x1행렬  
y  = a+b   # 4x3행렬 + 4x1행렬
                                      #브로드캐스팅에 의해 4x1행렬-> 4x3행렬로 늘어남.
sess = tf.Session()
init = tf.initialize_all_variables() #변수를 초기화하는 과정
sess.run(init)
result = sess.run(y)

print (result)

[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]]


![그림2](img/broadcasting2.gif)

반면, 위 그림은 4x3행렬과 1x4행렬의 더하기 연산을 시도하는데, 더하기가 되어야 하는 열원소의 갯수 또는 행의 원소의 갯수가 동일하지 않기 때문에 broadcasting이 일어날 수 없다. 

![title](img/broadcasting3.gif)

그러나 예외적으로 위 그림은 4x1행렬과 1x3행렬의 더하기 연산을 시도하는데, 열, 행의 갯수가 모두 맞지 않지만 각각의 크기가 1이기 때문에 그림과 같은 broadcasting이 일어난다. 이를 외적이라고 부른다.


In [27]:
import tensorflow as tf

a  =tf.Variable([[0],[10],[20],[30]],dtype=tf.float32)  # 4x1행렬
b  =tf.Variable([[0,1,2]],dtype=tf.float32) # 1x3행렬  
y  =a+b # 4x1행렬 + 1x3행렬
        #브로드캐스팅에 의해 4x1행렬-> 4x3행렬, 1x3행렬-> 4x3행렬로 각각 늘어남.
sess = tf.Session()
init = tf.initialize_all_variables() #변수를 초기화하는 과정
sess.run(init)
result = sess.run(y)

print (result)

[[  0.   1.   2.]
 [ 10.  11.  12.]
 [ 20.  21.  22.]
 [ 30.  31.  32.]]


## 연습 #2 : Broadcasting 연습

In [ ]:
## 연습 #2